import React from "react";
import PageHero from "@/components/PageHero";
import SEOMeta from "@/components/SEOMeta";

const LEGAL_META = {
    privacy: {
        title: "Privacy Policy",
        desc: "Review Studio Form's Privacy Policy, data privacy guidelines, data residency details, and user rights.",
        keywords: "privacy policy, data security, data residency India, user rights Studio Form"
    },
    terms: {
        title: "Terms of Service",
        desc: "Review Studio Form's Terms of Service, usage policies, intellectual property rights, and service levels.",
        keywords: "terms of service, user agreement, SLA policy, governing law India, terms and conditions"
    },
    refund: {
        title: "Refund Policy",
        desc: "Review Studio Form's Refund Policy, cancellation terms, cooling-off window, and refund eligibility.",
        keywords: "refund policy, cancellation policy, subscription refund, billing queries"
    },
    shipping: {
        title: "Shipping & Delivery Policy",
        desc: "Review Studio Form's digital delivery and service activation guidelines.",
        keywords: "shipping policy, delivery policy, digital delivery, service activation"
    },
    cancellation: {
        title: "Cancellation Policy",
        desc: "Review how to cancel subscriptions, active plans, or custom service contracts with Studio Form.",
        keywords: "cancellation policy, terminate subscription, cancel plan"
    }
};

const getLegalStructuredData = (kind, title, desc) => ({
    "@context": "https://schema.org",
    "@type": "WebPage",
    "name": `${title} | Studio Form`,
    "description": desc,
    "url": `https://www.studioform.app/${kind}`
});

const COPY = {
    privacy: {
        title: "Privacy",
        accent: "Policy.",
        cmd: "studioform --privacy",
        body: [
            ["Collection & DPDP Compliance", "We process personal data in compliance with India's Digital Personal Data Protection Act (DPDP Act), 2023. We collect information you knowingly provide (name, work email, phone, company, uploaded files, chat conversations, and voice recordings) and automated analytics data."],
            ["Consent & Legal Basis", "We process personal data based on your explicit, specific, and revocable consent. You may withdraw consent at any time. Processing is also carried out to fulfill service requests under standard contract terms."],
            ["Third-Party Processors", "We share necessary data with trusted subprocessors for infrastructure and analytics: Vercel (hosting), Render (backends), MongoDB Atlas (database), AWS (cloud compute), Google Analytics & GTM (traffic analytics), OpenAI & Anthropic (LLM endpoints). We do not sell your data."],
            ["Data Retention Limits", "We retain personal data only as long as necessary for the purpose: (1) Contact forms & leads: retained for 12 months post sales cycle; (2) Newsletters: until subscription cancellation; (3) Analytics: 26 months under GA4 telemetry configurations."],
            ["Your Rights & Deletion", "Under the DPDP Act, you have the right to access, correct, or request erasure of your data. To exercise these rights, email our Grievance Officer at privacy@studioform.app. Erasure requests are processed within 14 working days."],
            ["Security Protocols", "We implement industry-standard security measures including end-to-end HTTPS, encryption-in-transit, strict access control lists, and automated threat monitoring."],
        ],
    },
    terms: {
        title: "Terms of",
        accent: "Service.",
        cmd: "studioform --terms",
        body: [
            ["Acceptance", "By using studioform.app, our APIs, and AI models, you agree to these Terms. If you do not agree, please do not access or use the platform."],
            ["AI System Disclosures", "Studio Form provides AI services and agent systems. You acknowledge that AI-generated outputs may contain hallucinations, errors, or inaccuracies. You remain responsible for reviewing and verifying all AI outputs before relying on them. Uploaded inputs may be processed by third-party model providers."],
            ["Acceptable Use Policies", "You agree not to reverse-engineer our models, bypass security barriers, or use the service to generate harmful, unlawful, or discriminatory content. Violations will result in immediate suspension."],
            ["Intellectual Property", "Studio Form retains all ownership rights of its proprietary software, voice synthesis architectures, and codebases. Customer data and model inputs remain the sole property of the customer."],
            ["Limitation of Liability", "To the maximum extent permitted by law, our aggregate liability is limited to fees paid by you in the 12 months preceding the claim. We are not liable for business loss or data inaccuracies generated by LLMs."],
            ["Governing Law & Jurisdiction", "These terms are governed by the laws of India. Any disputes arising out of these terms shall be subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka."],
        ],
    },
    refund: {
        title: "Refund",
        accent: "Policy.",
        cmd: "studioform --refund",
        body: [
            ["Scope", "This policy applies to self-serve purchases from studioform.app. Enterprise contracts follow their own refund terms."],
            ["Cooling-off window", "If you cancel within 7 days of purchase and have not consumed material product value, we offer a full refund."],
            ["Pro-rata refunds", "For annual subscriptions cancelled mid-term, we issue a pro-rata refund on the unused months minus a 10% administrative fee."],
            ["Non-refundable items", "Custom development engagements, GPU reservations, and education programs that have started are non-refundable."],
            ["How to claim", "Email billing@studioform.app with your order ID. We process verified refunds within 7 working days."],
        ],
    },
    shipping: {
        title: "Shipping &",
        accent: "Delivery.",
        cmd: "studioform --shipping",
        body: [
            ["Digital Delivery", "Since all products and services provided by Studio Form are digital software-as-a-service (SaaS) platforms, custom workflow scripts, or API integrations, no physical shipping takes place."],
            ["Activation Timeline", "Self-serve SaaS plans are activated immediately upon successful payment confirmation. Custom voice agents, databases, and ML models are delivered according to agreed timeline structures (typically 2-4 weeks)."],
            ["Access Credentials", "Login details, API keys, and private cluster keys are dispatched electronically to your registered workspace email address."],
        ],
    },
    cancellation: {
        title: "Cancellation",
        accent: "Policy.",
        cmd: "studioform --cancellation",
        body: [
            ["How to Cancel", "You can cancel your subscription at any time via your account billing dashboard, or by writing to support@studioform.app."],
            ["Effect of Cancellation", "Upon cancellation, your plan remains active until the end of your current billing period. No additional recurring charges will be generated."],
            ["Custom Engagements", "Cancellation terms for dedicated GPU clusters, model fine-tuning contracts, and workshops are governed by their respective custom Statement of Work (SOW)."],
        ],
    },
};

export default function Legal({ kind = "privacy" }) {
    const c = COPY[kind];
    const meta = LEGAL_META[kind] || { title: "Legal Policy", desc: "Studio Form legal policies.", keywords: "legal, policy" };
    return (
        <div>
            <SEOMeta
                title={meta.title}
                description={meta.desc}
                keywords={meta.keywords}
                structuredData={getLegalStructuredData(kind, meta.title, meta.desc)}
            />
            <PageHero command={c.cmd} title={c.title} accent={c.accent} subtitle="Last updated: February 2026. Plain English, no dark patterns." />
            <section className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-8">
                {c.body.map(([t, b]) => (
                    <div key={t}>
                        <h3 className="font-display text-2xl font-bold">{t}</h3>
                        <p className="mt-3 text-white/65 leading-relaxed text-sm">{b}</p>
                    </div>
                ))}
                <div className="font-mono text-xs text-white/40 pt-6 border-t border-white/10">$ studioform --legal &nbsp;→&nbsp; for questions write to legal@studioform.app</div>
            </section>
        </div>
    );
}
